version: '3.7'

volumes:
  postgres_data:
  mongo_data_v5:

networks:
  backend:

services:
  postgres:
    container_name: codever-postgres
    image: postgres:16-alpine
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: codever-keycloak
    image: quay.io/keycloak/keycloak:24.0
    networks:
      - backend
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_RELATIVE_PATH: /auth
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: Pa55w0rd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    command: start-dev --import-realm
    ports:
      - 8480:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./docker-compose-setup/keycloak-export-import:/opt/keycloak/data/import:ro
      - ./apps/codever-keycloak-theme/codever/:/opt/keycloak/themes/codever/

  mongo:
    container_name: codever-mongo
    image: mongo:5.0
    networks:
      - backend
    environment:
      - MONGO_INITDB_DATABASE=dev-bookmarks
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - ./docker-compose-setup/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_data_v5:/data/db
