/**
 * Decided not to use language eventually, as it is automatically recognised and we have tags and comments...
 *
 */
// see - https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md
export const code_snippet_languages = [
  {'name': '1c', 'code': '1C'},
  {'name': '4D', 'code': '4d'},
  {'name': 'ABNF', 'code': 'abnf'},
  {'name': 'Access logs', 'code': 'accesslog'},
  {'name': 'Ada', 'code': 'ada'},
  {'name': 'ARM assembler', 'code': 'armasm'},
  {'name': 'AVR assembler', 'code': 'avrasm'},
  {'name': 'ActionScript', 'code': 'actionscript'},
  {'name': 'Alan', 'code': 'alan'},
  {'name': 'AngelScript', 'code': 'angelscript'},
  {'name': 'Apache', 'code': 'apache'},
  {'name': 'AppleScript', 'code': 'applescript'},
  {'name': 'Arcade', 'code': 'arcade'},
  {'name': 'AsciiDoc', 'code': 'adoc'},
  {'name': 'AspectJ', 'code': 'AspectJ'},
  {'name': 'AutoHotkey', 'code': 'autohotkey'},
  {'name': 'AutoIt', 'code': 'autoit'},
  {'name': 'Awk', 'code': 'awk'},
  {'name': 'Axapta', 'code': 'axapta'},
  {'name': 'Bash', 'code': 'bash'},
  {'name': 'Basic', 'code': 'basic'},
  {'name': 'BNF', 'code': 'bnf'},
  {'name': 'Brainfuck', 'code': 'brainfuck'},
  {'name': 'C#', 'code': 'csharp'},
  {'name': 'C', 'code': 'h'},
  {'name': 'JavaScript', 'code': 'javascript'},
  {'name': 'C++', 'code': 'cpp'},
  {'name': 'CSS', 'code': 'css' },
  {'name': 'C/AL', 'code': 'cal' },
  {'name': 'Cache Object Script', 'code': 'cos' },
  {'name': 'CMake', 'code': 'cmake' },
  {'name': 'CSP', 'code': 'csp' },
  {'name': 'CSS', 'code': 'css' },
  {'name': 'Cap’n Proto', 'code': 'capnproto' },
  {'name': 'Clojure', 'code': 'clojure' },
  {'name': 'CoffeeScript', 'code': 'coffeescript' },
  {'name': 'Crystal', 'code': 'crystal' },
  {'name': 'Cypher (Neo4j)', 'code': 'cypher' },
  {'name': 'D', 'code': 'd' },
  {'name': 'D', 'code': 'd' },
  {'name': 'DNS Zone file', 'code': 'dns' },
  {'name': 'DOS', 'code': 'dos'},
  {'name': 'Dart', 'code': 'dart'},
  {'name': 'Delphi', 'code': 'delphi'},
  {'name': 'Diff', 'code': 'diff'},
  {'name': 'Django', 'code': 'django'},
  {'name': 'Dockerfile', 'code': 'Dockerfile'},
  {'name': 'dsconfig', 'code': 'dsconfig'},
  {'name': 'DTS (Device Tree)', 'code': 'dts'},
  {'name': 'Dust', 'code': 'dust'},
  {'name': 'Dylan', 'code': 'dylan'},
  {'name': 'EBNF', 'code': 'ebnf'},
  {'name': 'Elixir', 'code': 'elixir'},
  {'name': 'Elm', 'code': 'elm'},
  {'name': 'Erlang', 'code': 'erlang'},
  {'name': 'Excel', 'code': 'excel'},
  {'name': 'F#', 'code': 'fsharp'},
  {'name': 'FIX', 'code': 'fix'},
  {'name': 'Fortran', 'code': 'fortran'},


  {'name': 'Java', 'code': 'java' },
  {'name': 'JSON', 'code': 'json' },
  {'name': 'HTML', 'code': 'html' },
  {'name': 'Typescript', 'code': 'typescript' }
];
