const ENV = {
  'DEV': 'development',
  'TEST': 'test',
  'PROD': 'production'
}

const MAX_NUMBER_OF_TAGS = 8;

const MAX_NUMBER_OF_CHARS_FOR_DESCRIPTION = 1500;

const MAX_NUMBER_OF_LINES_FOR_DESCRIPTION = 100;

const MAX_NUMBER_RETURNED_RESULTS = 55;

const MAX_NUMBER_STORED_BOOKMARKS_FOR_PERSONAL_STORE = 50;

module.exports = {
  ENV,
  MAX_NUMBER_OF_TAGS,
  MAX_NUMBER_OF_CHARS_FOR_DESCRIPTION,
  MAX_NUMBER_OF_LINES_FOR_DESCRIPTION,
  MAX_NUMBER_RETURNED_RESULTS,
  MAX_NUMBER_STORED_BOOKMARKS_FOR_PERSONAL_STORE
}
