const ENV = {
  'DEV': 'development',
  'TEST': 'test',
  'PROD': 'production'
}

const MAX_NUMBER_OF_TAGS = 8;

const MAX_NUMBER_OF_CHARS_FOR_DESCRIPTION = 1500;

const MAX_NUMBER_OF_LINES_FOR_DESCRIPTION = 100;

module.exports = {
  ENV,
  MAX_NUMBER_OF_TAGS,
  MAX_NUMBER_OF_CHARS_FOR_DESCRIPTION,
  MAX_NUMBER_OF_LINES_FOR_DESCRIPTION
}
